from __future__ import annotations

from typing import Any

SAFETY_EXPLAINER = {
    "navigation_only": "Navigation links and aliases are safe entry points only. They do not submit orders, cancel orders, approve trades, arm live trading, disable read-only mode, or bypass backend safety gates.",
    "v2_live_controls": "The v2 live console remains the safety-critical live-control plane and compatibility layer. Live-adjacent actions still require backend gates, audit logging, approval, and typed confirmations.",
    "v3_operator_os": "The v3 Operator OS is the review, workflow, graph, analytics, data, task, workspace, and cockpit surface. It does not convert review completion into trade approval.",
    "ai_copilot": "AI Copilot outputs are drafts for human review. They are not financial advice, not trade approval, and cannot place, cancel, arm, or disable safety gates.",
    "ai_edge_research": "AI Edge Research packets are evidence-backed drafts with citations, contradictions, missing information, probability drafts, and calibration records. They are not financial advice, not trade approval, and do not search the web unless every explicit web-search gate is enabled.",
    "opportunity_review": "Opportunity Review Workbench records, operator notes, watchlist states, paper-review queue states, and AI Edge packet lifecycle updates are review-only and cannot place, cancel, approve, or arm live trading.",
    "ai_news_odds": "AI News Odds adjustments update internal draft fair probabilities for review only. Source weighting and corroboration do not prove truth, and accepted adjustments never place or cancel orders.",
    "cross_market_arbitrage": "Cross-market arbitrage candidates are review-only comparisons across venue snapshots. They are not guaranteed profits and never auto-submit orders.",
    "platform": "Platform diagnostics, schemas, migrations, plugins, and route inventories are local operational aids and do not mutate live trading state.",
}

NAVIGATION_ITEMS: list[dict[str, Any]] = [
    {
        "id": "home",
        "title": "Home / Unified Operator Dashboard",
        "canonical_path": "/",
        "alias_path": "/home",
        "description": "Product home with links into the operator OS, AI Copilot, live controls, platform diagnostics, cockpit, tasks, data, analytics, and settings.",
        "section": "Home",
        "safety_class": "informational",
        "mutation_risk": "read-only",
        "recommended_entry": False,
        "visible_in_global_nav": True,
        "visible_in_root_dashboard": True,
        "visible_in_v2_bridge": True,
        "visible_in_v3_bridge": True,
        "visible_in_ai_bridge": True,
        "sort_order": 10,
    },
    {
        "id": "operator_os",
        "title": "Operator Intelligence OS",
        "canonical_path": "/v3",
        "alias_path": "/operator-os",
        "description": "Recommended starting point for command center, workflows, search, graph, analytics context, task/workspace/cockpit entry, and platform/AI bridge cards.",
        "section": "Operator OS",
        "safety_class": "informational",
        "mutation_risk": "read-only",
        "recommended_entry": True,
        "visible_in_global_nav": True,
        "visible_in_root_dashboard": True,
        "visible_in_v2_bridge": True,
        "visible_in_v3_bridge": True,
        "visible_in_ai_bridge": True,
        "sort_order": 20,
    },
    {
        "id": "ai_copilot",
        "title": "AI Copilot",
        "canonical_path": "/v3/ai",
        "alias_path": "/ai",
        "description": "Draft/review summaries, OpenAI and local LLM settings, model recommendations, prompt governance, AI suggestions, audit, and ChatGPT connector blueprint.",
        "section": "AI Copilot",
        "safety_class": "review-only",
        "mutation_risk": "draft/review only",
        "recommended_entry": False,
        "visible_in_global_nav": True,
        "visible_in_root_dashboard": True,
        "visible_in_v2_bridge": True,
        "visible_in_v3_bridge": True,
        "visible_in_ai_bridge": True,
        "sort_order": 30,
    },
    {
        "id": "live_controls",
        "title": "Live Controls",
        "canonical_path": "/v2-live",
        "alias_path": "/live",
        "description": "Safety-critical live-control plane, readiness, risk, audit, emergency controls, and fail-closed live-adjacent review surfaces.",
        "section": "Live Controls",
        "safety_class": "gated-live-control",
        "mutation_risk": "live-control gated",
        "recommended_entry": False,
        "visible_in_global_nav": True,
        "visible_in_root_dashboard": True,
        "visible_in_v2_bridge": True,
        "visible_in_v3_bridge": True,
        "visible_in_ai_bridge": True,
        "sort_order": 40,
    },
    {
        "id": "ai_edge_research",
        "title": "AI Edge Research",
        "canonical_path": "/v3/ai/edge",
        "alias_path": "/edge",
        "description": "Evidence-backed AI edge research packets, source citations, web-search dry-run planning, local LLM evidence review, draft probabilities, and calibration tracking.",
        "section": "AI & Research",
        "safety_class": "review-only",
        "mutation_risk": "draft/review only",
        "recommended_entry": False,
        "visible_in_global_nav": True,
        "visible_in_root_dashboard": True,
        "visible_in_v2_bridge": True,
        "visible_in_v3_bridge": True,
        "visible_in_ai_bridge": True,
        "sort_order": 45,
    },
    {
        "id": "ai_news_odds",
        "title": "AI News Odds",
        "canonical_path": "/v3/ai/news-odds",
        "alias_path": "/news-odds",
        "description": "Source-weighted news/evidence engine for draft fair-probability adjustments, corroboration scoring, duplicate detection, and AI Edge packet integration. Review-only; no live mutation.",
        "section": "AI & Research",
        "safety_class": "review-only",
        "mutation_risk": "draft/review only",
        "recommended_entry": True,
        "visible_in_global_nav": True,
        "visible_in_root_dashboard": True,
        "visible_in_v2_bridge": True,
        "visible_in_v3_bridge": True,
        "visible_in_ai_bridge": True,
        "sort_order": 46,
    },
    {
        "id": "market_edge_recommendations",
        "title": "Market Edge Recommendations",
        "canonical_path": "/api/markets/edge-legend",
        "alias_path": "/edge/legend",
        "description": "Deterministic YES/NO/HOLD recommendation legend, favorite-vs-edge explanation, market-family ranking helper, and draft-only safety boundary.",
        "section": "AI & Research",
        "safety_class": "review-only",
        "mutation_risk": "draft/review only",
        "recommended_entry": False,
        "visible_in_global_nav": False,
        "visible_in_root_dashboard": True,
        "visible_in_v2_bridge": True,
        "visible_in_v3_bridge": True,
        "visible_in_ai_bridge": True,
        "sort_order": 47,
    },
    {
        "id": "cross_market_arbitrage",
        "title": "Cross-Market Arbitrage",
        "canonical_path": "/v3/arbitrage",
        "alias_path": "/arbitrage",
        "description": "Review-only Polymarket/Kalshi/competitor venue comparison for candidate arbitrage, fees, slippage, liquidity, and resolution mismatch risk.",
        "section": "AI & Research",
        "safety_class": "review-only",
        "mutation_risk": "draft/review only",
        "recommended_entry": True,
        "visible_in_global_nav": True,
        "visible_in_root_dashboard": True,
        "visible_in_v2_bridge": True,
        "visible_in_v3_bridge": True,
        "visible_in_ai_bridge": True,
        "sort_order": 47.5,
    },
    {
        "id": "opportunity_review_workbench",
        "title": "Opportunity Review Workbench",
        "canonical_path": "/v3/opportunities",
        "alias_path": "/opportunity-review",
        "description": "Review-only operator workbench for market drilldowns, edge explanations, AI Edge packet lifecycle, operator notes, watchlist states, and paper-review candidates.",
        "section": "AI & Research",
        "safety_class": "review-only",
        "mutation_risk": "draft/review only",
        "recommended_entry": True,
        "visible_in_global_nav": True,
        "visible_in_root_dashboard": True,
        "visible_in_v2_bridge": True,
        "visible_in_v3_bridge": True,
        "visible_in_ai_bridge": True,
        "sort_order": 48,
    },
    {
        "id": "feature_readiness_review",
        "title": "Feature Readiness",
        "canonical_path": "/v3/feature-readiness",
        "alias_path": "/feature-readiness",
        "description": "Truthful operator readiness page for working, partial, config-required, scaffolded, disabled, unavailable, and error statuses with local acknowledgement records.",
        "section": "Operator OS",
        "safety_class": "review-only",
        "mutation_risk": "local audit only",
        "recommended_entry": True,
        "visible_in_global_nav": True,
        "visible_in_root_dashboard": True,
        "visible_in_v2_bridge": True,
        "visible_in_v3_bridge": True,
        "visible_in_ai_bridge": True,
        "sort_order": 48.5,
    },
    {
        "id": "market_detail_drilldown",
        "title": "Market Detail / Opportunity Review",
        "canonical_path": "/v3/markets/demo_france_world_cup",
        "alias_path": "/market-review",
        "description": "Safe drilldown page pattern for one market with YES/NO prices, model fair source, edge explanation, family rank, AI Edge lifecycle, and operator notes.",
        "section": "AI & Research",
        "safety_class": "review-only",
        "mutation_risk": "draft/review only",
        "recommended_entry": False,
        "visible_in_global_nav": False,
        "visible_in_root_dashboard": True,
        "visible_in_v2_bridge": True,
        "visible_in_v3_bridge": True,
        "visible_in_ai_bridge": True,
        "sort_order": 49,
    },
    {
        "id": "market_family_comparison",
        "title": "Market Family Comparison",
        "canonical_path": "/v3/markets/family/2026_fifa_world_cup_winner",
        "alias_path": "/family-review",
        "description": "Conservative mutually-exclusive market-family comparison page that separates group favorite from draft wager edge.",
        "section": "AI & Research",
        "safety_class": "review-only",
        "mutation_risk": "draft/review only",
        "recommended_entry": False,
        "visible_in_global_nav": False,
        "visible_in_root_dashboard": True,
        "visible_in_v2_bridge": True,
        "visible_in_v3_bridge": True,
        "visible_in_ai_bridge": True,
        "sort_order": 49.5,
    },
    {
        "id": "ai_edge_packet_lifecycle",
        "title": "AI Edge Packet Lifecycle",
        "canonical_path": "/v3/ai/edge/packets",
        "alias_path": "/edge-packets",
        "description": "Draft to evidence-attached to AI-analyzed to operator-reviewed lifecycle for AI Edge packets; review-only and no-live-mutation.",
        "section": "AI & Research",
        "safety_class": "review-only",
        "mutation_risk": "draft/review only",
        "recommended_entry": False,
        "visible_in_global_nav": False,
        "visible_in_root_dashboard": True,
        "visible_in_v2_bridge": True,
        "visible_in_v3_bridge": True,
        "visible_in_ai_bridge": True,
        "sort_order": 49.8,
    },
    {
        "id": "platform",
        "title": "Platform Health",
        "canonical_path": "/v3/platform",
        "alias_path": "/platform",
        "description": "Diagnostics, route inventory, schema inventory, migrations, plugin manifests, storage compatibility, and release health.",
        "section": "Platform",
        "safety_class": "informational",
        "mutation_risk": "read-only",
        "recommended_entry": False,
        "visible_in_global_nav": True,
        "visible_in_root_dashboard": True,
        "visible_in_v2_bridge": True,
        "visible_in_v3_bridge": True,
        "visible_in_ai_bridge": True,
        "sort_order": 50,
    },
    {
        "id": "cockpit",
        "title": "Operator Cockpit",
        "canonical_path": "/v3/cockpit",
        "alias_path": "/cockpit",
        "description": "Multi-panel review workspace for tasks, source previews, dependencies, packets, data, and decision context.",
        "section": "Tasks / Workspace / Cockpit",
        "safety_class": "review-only",
        "mutation_risk": "draft/review only",
        "recommended_entry": False,
        "visible_in_global_nav": True,
        "visible_in_root_dashboard": True,
        "visible_in_v2_bridge": True,
        "visible_in_v3_bridge": True,
        "visible_in_ai_bridge": True,
        "sort_order": 60,
    },
    {
        "id": "workspace",
        "title": "Guided Workspace",
        "canonical_path": "/v3/workspace",
        "alias_path": "/workspace",
        "description": "Guided daily/weekly reviews, source previews, blocked-task review, dependencies, and review packets.",
        "section": "Tasks / Workspace / Cockpit",
        "safety_class": "review-only",
        "mutation_risk": "draft/review only",
        "recommended_entry": False,
        "visible_in_global_nav": True,
        "visible_in_root_dashboard": True,
        "visible_in_v2_bridge": False,
        "visible_in_v3_bridge": True,
        "visible_in_ai_bridge": True,
        "sort_order": 70,
    },
    {
        "id": "tasks",
        "title": "Task Planner",
        "canonical_path": "/v3/tasks",
        "alias_path": "/tasks",
        "description": "Task inbox, task board, daily ops, weekly planning, cadence, templates, and exports. Task completion is not trade approval.",
        "section": "Tasks / Workspace / Cockpit",
        "safety_class": "review-only",
        "mutation_risk": "draft/review only",
        "recommended_entry": False,
        "visible_in_global_nav": True,
        "visible_in_root_dashboard": True,
        "visible_in_v2_bridge": True,
        "visible_in_v3_bridge": True,
        "visible_in_ai_bridge": True,
        "sort_order": 80,
    },
    {
        "id": "datasets",
        "title": "Datasets",
        "canonical_path": "/v3/datasets",
        "alias_path": "/datasets",
        "description": "Snapshot collector, dataset builder, quality, provenance, replay readiness, and secret-safe exports.",
        "section": "Data / Datasets",
        "safety_class": "read-only-action",
        "mutation_risk": "read-only",
        "recommended_entry": False,
        "visible_in_global_nav": True,
        "visible_in_root_dashboard": True,
        "visible_in_v2_bridge": False,
        "visible_in_v3_bridge": True,
        "visible_in_ai_bridge": False,
        "sort_order": 90,
    },
    {
        "id": "freshness",
        "title": "Freshness Scheduler",
        "canonical_path": "/v3/freshness",
        "alias_path": "/freshness",
        "description": "Read-only collection planning, freshness findings, notification triage, readiness, and history.",
        "section": "Freshness / Scheduler",
        "safety_class": "read-only-action",
        "mutation_risk": "read-only",
        "recommended_entry": False,
        "visible_in_global_nav": True,
        "visible_in_root_dashboard": True,
        "visible_in_v2_bridge": False,
        "visible_in_v3_bridge": True,
        "visible_in_ai_bridge": False,
        "sort_order": 100,
    },
    {
        "id": "simulation",
        "title": "Simulation / Replay",
        "canonical_path": "/v3/simulation",
        "alias_path": "/simulation",
        "description": "Replay, process backtests, no-trade review, scenario evaluation, and simulation reports. Descriptive only.",
        "section": "Simulation / Replay",
        "safety_class": "review-only",
        "mutation_risk": "draft/review only",
        "recommended_entry": False,
        "visible_in_global_nav": True,
        "visible_in_root_dashboard": True,
        "visible_in_v2_bridge": False,
        "visible_in_v3_bridge": True,
        "visible_in_ai_bridge": False,
        "sort_order": 110,
    },
    {
        "id": "analytics",
        "title": "Analytics / Learning",
        "canonical_path": "/v3/analytics",
        "alias_path": "/analytics",
        "description": "Decision-quality, calibration, evidence, portfolio, governance, and learning-report views. Not predictive advice.",
        "section": "Analytics / Learning",
        "safety_class": "informational",
        "mutation_risk": "read-only",
        "recommended_entry": False,
        "visible_in_global_nav": True,
        "visible_in_root_dashboard": True,
        "visible_in_v2_bridge": False,
        "visible_in_v3_bridge": True,
        "visible_in_ai_bridge": False,
        "sort_order": 120,
    },
    {
        "id": "settings",
        "title": "Settings / Configuration",
        "canonical_path": "/settings",
        "alias_path": "/configuration",
        "description": "Configuration health, setup wizard, sanitized exports, provider status, and safe environment guidance.",
        "section": "Settings / Configuration",
        "safety_class": "configuration",
        "mutation_risk": "configuration",
        "recommended_entry": False,
        "visible_in_global_nav": True,
        "visible_in_root_dashboard": True,
        "visible_in_v2_bridge": True,
        "visible_in_v3_bridge": True,
        "visible_in_ai_bridge": True,
        "sort_order": 130,
    },
    {
        "id": "system_map",
        "title": "System Map / Route Map",
        "canonical_path": "/system-map",
        "alias_path": "/routes",
        "description": "Unified route map showing canonical paths, friendly aliases, safety class, mutation risk, and section purpose.",
        "section": "Help / Route Map",
        "safety_class": "informational",
        "mutation_risk": "read-only",
        "recommended_entry": False,
        "visible_in_global_nav": True,
        "visible_in_root_dashboard": True,
        "visible_in_v2_bridge": True,
        "visible_in_v3_bridge": True,
        "visible_in_ai_bridge": True,
        "sort_order": 140,
    },
]

ALIAS_TARGETS: dict[str, str] = {
    "/home": "/",
    "/operator-os": "/v3",
    "/ai": "/v3/ai",
    "/ai/settings": "/v3/ai/settings",
    "/ai/providers": "/v3/ai/providers",
    "/ai/openai": "/v3/ai/openai",
    "/ai/local-llm": "/v3/ai/local-llm",
    "/ai/model-recommendations": "/v3/ai/model-recommendations",
    "/ai/edge": "/v3/ai/edge",
    "/edge": "/v3/ai/edge",
    "/edge/new": "/v3/ai/edge/new",
    "/edge/packets": "/v3/ai/edge/packets",
    "/edge/evidence": "/v3/ai/edge/evidence",
    "/edge/calibration": "/v3/ai/edge/calibration",
    "/edge/settings": "/v3/ai/edge/settings",
    "/news-odds": "/v3/ai/news-odds",
    "/ai/news-odds": "/v3/ai/news-odds",
    "/news-odds/run": "/v3/ai/news-odds/run",
    "/news-odds/adjustments": "/v3/ai/news-odds/adjustments",
    "/news-odds/source-weights": "/v3/ai/news-odds/source-weights",
    "/edge/legend": "/api/markets/edge-legend",
    "/edge/families": "/api/markets/family-rankings",
    "/arbitrage": "/v3/arbitrage",
    "/cross-market-arbitrage": "/v3/arbitrage",
    "/opportunity-review": "/v3/opportunities",
    "/opportunity-workbench": "/v3/opportunities",
    "/market-review": "/v3/markets/demo_france_world_cup",
    "/family-review": "/v3/markets/family/2026_fifa_world_cup_winner",
    "/edge-packets": "/v3/ai/edge/packets",
    "/platform": "/v3/platform",
    "/cockpit": "/v3/cockpit",
    "/workspace": "/v3/workspace",
    "/tasks": "/v3/tasks",
    "/datasets": "/v3/datasets",
    "/freshness": "/v3/freshness",
    "/simulation": "/v3/simulation",
    "/analytics": "/v3/analytics",
    "/live": "/v2-live",
    "/live-controls": "/v2-live",
    "/configuration": "/settings/configuration",
    "/feature-readiness": "/v3/feature-readiness",
    "/readiness-status": "/v3/feature-readiness",
}


def get_navigation_sections() -> list[dict[str, Any]]:
    sections: dict[str, list[dict[str, Any]]] = {}
    for item in sorted(NAVIGATION_ITEMS, key=lambda row: row["sort_order"]):
        sections.setdefault(item["section"], []).append(dict(item))
    return [{"label": section, "items": items} for section, items in sections.items()]


def get_global_nav_items() -> list[dict[str, Any]]:
    return [dict(item) for item in sorted(NAVIGATION_ITEMS, key=lambda row: row["sort_order"]) if item["visible_in_global_nav"]]


def get_primary_entry_points() -> list[dict[str, Any]]:
    return [dict(item) for item in sorted(NAVIGATION_ITEMS, key=lambda row: row["sort_order"]) if item["visible_in_root_dashboard"]]


def get_route_aliases() -> dict[str, str]:
    return dict(ALIAS_TARGETS)


def get_system_map() -> dict[str, Any]:
    items = [dict(item) for item in sorted(NAVIGATION_ITEMS, key=lambda row: row["sort_order"])]
    return {
        "recommended_starting_point": "/v3",
        "recommended_starting_alias": "/operator-os",
        "items": items,
        "aliases": get_route_aliases(),
        "count": len(items),
        "alias_count": len(ALIAS_TARGETS),
        "navigation_links_are_safe_entry_points_only": True,
        "aliases_mutate_state": False,
        "aliases_bypass_backend_gates": False,
        "order_submitted": False,
        "order_cancelled": False,
        "live_trading_armed": False,
        "secret_values_returned": False,
        "includes_ai_edge_market_row_routes": True,
        "includes_opportunity_review_workbench": True,
        "includes_market_detail_pages": True,
        "includes_market_family_comparison": True,
        "includes_ai_edge_packet_lifecycle": True,
        "includes_ai_news_odds_adjustment_engine": True,
        "includes_ai_news_source_weighting": True,
        "includes_ai_news_corroboration_scoring": True,
        "includes_ai_news_duplicate_detection": True,
        "includes_cross_market_arbitrage": True,
        "cross_market_arbitrage_is_review_only": True,
        "arbitrage_candidates_are_not_guaranteed_profit": True,
        "ai_news_odds_adjustments_are_review_only": True,
        "source_weighting_does_not_imply_truth": True,
        "corroboration_does_not_imply_certainty": True,
        "opportunity_review_records_are_review_only": True,
        "watchlist_review_only": True,
        "paper_review_draft_only": True,
        "favorite_ranking_does_not_imply_edge": True,
        "edge_recommendations_are_review_only": True,
        "safety_explainer": get_safety_explainer(),
    }


def get_safety_explainer() -> dict[str, str]:
    return dict(SAFETY_EXPLAINER)
